// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRS1x7F-tFkeoSzj2MCBilleDMgk6i718',
    appId: '1:412377351142:web:7e4efa5a60bf1a66afcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    authDomain: 'pocket-puppy-rattery-c3f07.firebaseapp.com',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
    measurementId: 'G-8PBYERMV29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDLqiUUvy_HvzqzNwaNIK_nTb0J02wzg',
    appId: '1:412377351142:android:e41d0c161dfd6c12afcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-aRUYJSmWUcdpNaRUMUkPTay-kVuNu0',
    appId: '1:412377351142:ios:60ad3e539ea34b0eafcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
    iosClientId: '412377351142-svcsa60q54t0649ls9hncchmibkoejp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPuppyRattery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj-aRUYJSmWUcdpNaRUMUkPTay-kVuNu0',
    appId: '1:412377351142:ios:a6888559e5386cdeafcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
    iosClientId: '412377351142-ralf8e3qvrgebg0t6l3deogs0va6ief6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPuppyRattery.RunnerTests',
  );
}
