// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeWtP97ZtsStt69hFwticfQzfpo7zNImM',
    appId: '1:1034726063302:web:22c8fc480808ca72e26bc7',
    messagingSenderId: '1034726063302',
    projectId: 'fir-bff42',
    authDomain: 'fir-bff42.firebaseapp.com',
    storageBucket: 'fir-bff42.appspot.com',
    measurementId: 'G-WZNDGEJG19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARmYsEJg0xAgaqtNZaGW4732cLcLRVxF8',
    appId: '1:1034726063302:android:93ba2d2917e5a842e26bc7',
    messagingSenderId: '1034726063302',
    projectId: 'fir-bff42',
    storageBucket: 'fir-bff42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALIUj5fj9O_b-BEVOH9biDxekVpkmMgTc',
    appId: '1:1034726063302:ios:f5c009412147f755e26bc7',
    messagingSenderId: '1034726063302',
    projectId: 'fir-bff42',
    storageBucket: 'fir-bff42.appspot.com',
    iosClientId: '1034726063302-ibk8vprnd34vtj4jigpspip5g058nutm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPuppyRattery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALIUj5fj9O_b-BEVOH9biDxekVpkmMgTc',
    appId: '1:1034726063302:ios:f5c009412147f755e26bc7',
    messagingSenderId: '1034726063302',
    projectId: 'fir-bff42',
    storageBucket: 'fir-bff42.appspot.com',
    iosClientId: '1034726063302-ibk8vprnd34vtj4jigpspip5g058nutm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPuppyRattery',
  );
}
